#!/bin/sh
# vim: ts=4 sw=4 et

do_submitcheck="/home/subjects/comp20006/local/project2/.do_submit_check"

svnhost="comp20006.eng.unimelb.edu.au"
runtests="/home/subjects/comp20006/local/project2/runtests"
progname="submit_check"
user=`whoami`

rootdir=`/bin/pwd`
tempdir="/tmp/submitcheck_comp20006.$$"
trap "cd /; /bin/rm -rf ${tempdir}" 0 1 2 3 15

mkdir -p ${tempdir}
rm -rf ${tempdir}/*

cd ${tempdir}

echo 'doing "svn co" of project2/submit for submit_check'
svn co https://${svnhost}/svn/${user}/project2/submit
if test $? -ne 0 -o ! -d submit
then
    echo "${progname}: checkout of project2/submit directory failed"
    cat CO_OUT
    exit 0
fi

cd submit

${do_submitcheck}

cd /
rm -rf ${tempdir}
exit 0
